# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the required packages
RUN apt-get update && \\
    apt-get install -y --no-install-recommends \\
        unixodbc-dev \\
        gcc \\
        g++ \\
        && \\
    rm -rf /var/lib/apt/lists/*

# Install the ODBC driver for SQL Server
RUN curl <https://packages.microsoft.com/keys/microsoft.asc> | apt-key add - && \\
    curl <https://packages.microsoft.com/config/debian/10/prod.list> > /etc/apt/sources.list.d/mssql-release.list && \\
    apt-get update && \\
    ACCEPT_EULA=Y apt-get install -y --no-install-recommends msodbcsql17 mssql-tools && \\
    apt-get clean && \\
    rm -rf /var/lib/apt/lists/*

# Install the Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Set the environment variables for the database connection
ENV SQL_SERVER="Localhost,1433"
ENV SQL_DATABASE="Trabajadores"
ENV SQL_USER="sa"
ENV SQL_PASSWORD="1234567890"

# Run the application
CMD [ "python", "main.py" ]
